// options.js

const options = [
    { value: 'salt', label: 'Salt' },
    { value: 'pepper', label: 'Pepper' },
    { value: 'olive oil', label: 'Olive Oil' },
    { value: 'garlic', label: 'Garlic' },
    { value: 'onion', label: 'Onion' },
    { value: 'butter', label: 'Butter' },
    { value: 'flour', label: 'Flour' },
    { value: 'sugar', label: 'Sugar' },
    { value: 'milk', label: 'Milk' },
    { value: 'egg', label: 'Egg' },
    { value: 'chicken breast', label: 'Chicken Breast' },
    { value: 'tomato', label: 'Tomato' },
    { value: 'carrot', label: 'Carrot' },
    { value: 'potato', label: 'Potato' },
    { value: 'basil', label: 'Basil' },
    { value: 'oregano', label: 'Oregano' },
    { value: 'thyme', label: 'Thyme' },
    { value: 'parsley', label: 'Parsley' },
    { value: 'cilantro', label: 'Cilantro' },
    { value: 'ginger', label: 'Ginger' },
    { value: 'soy sauce', label: 'Soy Sauce' },
    { value: 'vinegar', label: 'Vinegar' },
    { value: 'lemon', label: 'Lemon' },
    { value: 'lime', label: 'Lime' },
    { value: 'cheese', label: 'Cheese' },
    { value: 'parmesan', label: 'Parmesan' },
    { value: 'mozzarella', label: 'Mozzarella' },
    { value: 'cream', label: 'Cream' },
    { value: 'beef', label: 'Beef' },
    { value: 'pork', label: 'Pork' },
    { value: 'fish', label: 'Fish' },
    { value: 'shrimp', label: 'Shrimp' },
    { value: 'mushroom', label: 'Mushroom' },
    { value: 'broccoli', label: 'Broccoli' },
    { value: 'spinach', label: 'Spinach' },
    { value: 'bell pepper', label: 'Bell Pepper' },
    { value: 'cucumber', label: 'Cucumber' },
    { value: 'zucchini', label: 'Zucchini' },
    { value: 'eggplant', label: 'Eggplant' },
    { value: 'corn', label: 'Corn' },
    { value: 'peas', label: 'Peas' },
    { value: 'green beans', label: 'Green Beans' },
    { value: 'asparagus', label: 'Asparagus' },
    { value: 'cabbage', label: 'Cabbage' },
    { value: 'cauliflower', label: 'Cauliflower' },
    { value: 'celery', label: 'Celery' },
    { value: 'chili pepper', label: 'Chili Pepper' },
    { value: 'paprika', label: 'Paprika' },
    { value: 'cumin', label: 'Cumin' },
    { value: 'coriander', label: 'Coriander' },
    { value: 'turmeric', label: 'Turmeric' },
    { value: 'nutmeg', label: 'Nutmeg' },
    { value: 'cinnamon', label: 'Cinnamon' },
    { value: 'clove', label: 'Clove' },
    { value: 'allspice', label: 'Allspice' },
    { value: 'bay leaf', label: 'Bay Leaf' },
    { value: 'cardamom', label: 'Cardamom' },
    { value: 'black beans', label: 'Black Beans' },
    { value: 'kidney beans', label: 'Kidney Beans' },
    { value: 'chickpeas', label: 'Chickpeas' },
    { value: 'lentils', label: 'Lentils' },
    { value: 'quinoa', label: 'Quinoa' },
    { value: 'rice', label: 'Rice' },
    { value: 'pasta', label: 'Pasta' },
    { value: 'bread', label: 'Bread' },
    { value: 'tortilla', label: 'Tortilla' },
    { value: 'yogurt', label: 'Yogurt' },
    { value: 'honey', label: 'Honey' },
    { value: 'maple syrup', label: 'Maple Syrup' },
    { value: 'almonds', label: 'Almonds' },
    { value: 'walnuts', label: 'Walnuts' },
    { value: 'peanuts', label: 'Peanuts' },
    { value: 'cashews', label: 'Cashews' },
    { value: 'pecans', label: 'Pecans' },
    { value: 'hazelnuts', label: 'Hazelnuts' },
    { value: 'sunflower seeds', label: 'Sunflower Seeds' },
    { value: 'pumpkin seeds', label: 'Pumpkin Seeds' },
    { value: 'sesame seeds', label: 'Sesame Seeds' },
    { value: 'chia seeds', label: 'Chia Seeds' },
    { value: 'flax seeds', label: 'Flax Seeds' },
    { value: 'pine nuts', label: 'Pine Nuts' },
    { value: 'raisins', label: 'Raisins' },
    { value: 'dried cranberries', label: 'Dried Cranberries' },
    { value: 'dates', label: 'Dates' },
    { value: 'figs', label: 'Figs' },
    { value: 'prunes', label: 'Prunes' },
    { value: 'apples', label: 'Apples' },
    { value: 'bananas', label: 'Bananas' },
    { value: 'oranges', label: 'Oranges' },
    { value: 'strawberries', label: 'Strawberries' },
    { value: 'blueberries', label: 'Blueberries' },
    { value: 'raspberries', label: 'Raspberries' },
    { value: 'blackberries', label: 'Blackberries' },
    { value: 'grapes', label: 'Grapes' },
    { value: 'watermelon', label: 'Watermelon' },
    { value: 'cantaloupe', label: 'Cantaloupe' },
    { value: 'honeydew', label: 'Honeydew' },
    { value: 'kiwi', label: 'Kiwi' },
    { value: 'pineapple', label: 'Pineapple' },
    { value: 'mango', label: 'Mango' },
    { value: 'peach', label: 'Peach' },
    { value: 'plum', label: 'Plum' },
    { value: 'nectarine', label: 'Nectarine' },
    { value: 'cherry', label: 'Cherry' },
    { value: 'avocado', label: 'Avocado' },
    { value: 'coconut', label: 'Coconut' },
    { value: 'mandarin', label: 'Mandarin' },
    { value: 'grapefruit', label: 'Grapefruit' },
    { value: 'pomegranate', label: 'Pomegranate' },
    { value: 'cranberry', label: 'Cranberry' },
    { value: 'apple cider vinegar', label: 'Apple Cider Vinegar' },
    { value: 'balsamic vinegar', label: 'Balsamic Vinegar' },
    { value: 'red wine vinegar', label: 'Red Wine Vinegar' },
    { value: 'white wine vinegar', label: 'White Wine Vinegar' },
    { value: 'rice vinegar', label: 'Rice Vinegar' },
    { value: 'sherry vinegar', label: 'Sherry Vinegar' },
    { value: 'beer', label: 'Beer' },
    { value: 'white wine', label: 'White Wine' },
    { value: 'red wine', label: 'Red Wine' },
    { value: 'rum', label: 'Rum' },
    { value: 'vodka', label: 'Vodka' },
    { value: 'whiskey', label: 'Whiskey' },
    { value: 'bourbon', label: 'Bourbon' },
    { value: 'gin', label: 'Gin' },
    { value: 'tequila', label: 'Tequila' },
    { value: 'cognac', label: 'Cognac' },
    { value: 'brandy', label: 'Brandy' },
    { value: 'apple juice', label: 'Apple Juice' },
    { value: 'orange juice', label: 'Orange Juice' },
    { value: 'lemon juice', label: 'Lemon Juice' },
    { value: 'lime juice', label: 'Lime Juice' },
    { value: 'pineapple juice', label: 'Pineapple Juice' },
    { value: 'cranberry juice', label: 'Cranberry Juice' },
    { value: 'tomato juice', label: 'Tomato Juice' },
    { value: 'grapefruit juice', label: 'Grapefruit Juice' },
    { value: 'grape juice', label: 'Grape Juice' },
    { value: 'pomegranate juice', label: 'Pomegranate Juice' },
    { value: 'coconut water', label: 'Coconut Water' },
    { value: 'almond milk', label: 'Almond Milk' },
    { value: 'soy milk', label: 'Soy Milk' },
    { value: 'oat milk', label: 'Oat Milk' },
    { value: 'rice milk', label: 'Rice Milk' },
    { value: 'hemp milk', label: 'Hemp Milk' },
    { value: 'cashew milk', label: 'Cashew Milk' },
    { value: 'macadamia milk', label: 'Macadamia Milk' },
    { value: 'caramel', label: 'Caramel' },
    { value: 'chocolate', label: 'Chocolate' },
    { value: 'dark chocolate', label: 'Dark Chocolate' },
    { value: 'white chocolate', label: 'White Chocolate' },
    { value: 'cocoa powder', label: 'Cocoa Powder' },
    { value: 'vanilla extract', label: 'Vanilla Extract' },
    { value: 'almond extract', label: 'Almond Extract' },
    { value: 'peppermint extract', label: 'Peppermint Extract' },
    { value: 'coconut extract', label: 'Coconut Extract' },
    { value: 'orange extract', label: 'Orange Extract' },
    { value: 'lemon extract', label: 'Lemon Extract' },
    { value: 'banana extract', label: 'Banana Extract' },
    { value: 'maple extract', label: 'Maple Extract' },
    { value: 'hazelnut extract', label: 'Hazelnut Extract' },
    { value: 'rose water', label: 'Rose Water' },
    { value: 'orange blossom water', label: 'Orange Blossom Water' },
    { value: 'saffron', label: 'Saffron' },
    { value: 'white pepper', label: 'White Pepper' },
    { value: 'black pepper', label: 'Black Pepper' },
    { value: 'green peppercorn', label: 'Green Peppercorn' },
    { value: 'pink peppercorn', label: 'Pink Peppercorn' },
    { value: 'smoked paprika', label: 'Smoked Paprika' },
    { value: 'cayenne pepper', label: 'Cayenne Pepper' },
    { value: 'chili powder', label: 'Chili Powder' },
    { value: 'red pepper flakes', label: 'Red Pepper Flakes' },
    { value: 'hot sauce', label: 'Hot Sauce' },
    { value: 'barbecue sauce', label: 'Barbecue Sauce' },
    { value: 'teriyaki sauce', label: 'Teriyaki Sauce' },
    { value: 'hoisin sauce', label: 'Hoisin Sauce' },
    { value: 'fish sauce', label: 'Fish Sauce' },
    { value: 'oyster sauce', label: 'Oyster Sauce' },
    { value: 'worcestershire sauce', label: 'Worcestershire Sauce' },
    { value: 'ketchup', label: 'Ketchup' },
    { value: 'mustard', label: 'Mustard' },
    { value: 'mayonnaise', label: 'Mayonnaise' },
    { value: 'ranch dressing', label: 'Ranch Dressing' },
    { value: 'caesar dressing', label: 'Caesar Dressing' },
    { value: 'italian dressing', label: 'Italian Dressing' },
    { value: 'blue cheese dressing', label: 'Blue Cheese Dressing' },
    { value: 'thousand island dressing', label: 'Thousand Island Dressing' },
    { value: 'honey mustard', label: 'Honey Mustard' },
    { value: 'dijon mustard', label: 'Dijon Mustard' },
    { value: 'whole grain mustard', label: 'Whole Grain Mustard' },
    { value: 'sriracha', label: 'Sriracha' },
    { value: 'wasabi', label: 'Wasabi' },
    { value: 'hummus', label: 'Hummus' },
    { value: 'guacamole', label: 'Guacamole' },
    { value: 'salsa', label: 'Salsa' },
    { value: 'pico de gallo', label: 'Pico de Gallo' },
    { value: 'tabasco', label: 'Tabasco' },
    { value: 'frank\'s redhot', label: 'Frank\'s RedHot' },
    { value: 'cholula', label: 'Cholula' },
    { value: 'tahini', label: 'Tahini' },
    { value: 'nutella', label: 'Nutella' },
    { value: 'peanut butter', label: 'Peanut Butter' },
    { value: 'almond butter', label: 'Almond Butter' },
    { value: 'cashew butter', label: 'Cashew Butter' },
    { value: 'hazelnut spread', label: 'Hazelnut Spread' },
    { value: 'cookie butter', label: 'Cookie Butter' },
    { value: 'miso', label: 'Miso' },
    { value: 'tempeh', label: 'Tempeh' },
    { value: 'tofu', label: 'Tofu' },
    { value: 'seitan', label: 'Seitan' },
    { value: 'jackfruit', label: 'Jackfruit' },
    { value: 'edamame', label: 'Edamame' },
    { value: 'kimchi', label: 'Kimchi' },
    { value: 'sauerkraut', label: 'Sauerkraut' },
    { value: 'pickles', label: 'Pickles' },
    { value: 'pickled onions', label: 'Pickled Onions' },
    { value: 'pickled jalapenos', label: 'Pickled Jalapenos' },
    { value: 'pickled ginger', label: 'Pickled Ginger' },
    { value: 'pickled radish', label: 'Pickled Radish' },
    { value: 'pickled beets', label: 'Pickled Beets' },
    { value: 'pickled garlic', label: 'Pickled Garlic' },
    { value: 'pickled carrots', label: 'Pickled Carrots' },
    { value: 'pickled cucumber', label: 'Pickled Cucumber' },
    { value: 'kombucha', label: 'Kombucha' },
    { value: 'ginger beer', label: 'Ginger Beer' },
    { value: 'root beer', label: 'Root Beer' },
    { value: 'cola', label: 'Cola' },
    { value: 'orange soda', label: 'Orange Soda' },
    { value: 'lemon lime soda', label: 'Lemon Lime Soda' },
    { value: 'grapefruit soda', label: 'Grapefruit Soda' },
    { value: 'cream soda', label: 'Cream Soda' },
    { value: 'ginger ale', label: 'Ginger Ale' },
    { value: 'seltzer', label: 'Seltzer' },
    { value: 'tonic water', label: 'Tonic Water' },
    { value: 'club soda', label: 'Club Soda' },
    { value: 'sparkling water', label: 'Sparkling Water' },
    { value: 'still water', label: 'Still Water' },
    { value: 'coconut milk', label: 'Coconut Milk' },
    { value: 'coconut cream', label: 'Coconut Cream' },
    { value: 'sweetened condensed milk', label: 'Sweetened Condensed Milk' },
    { value: 'evaporated milk', label: 'Evaporated Milk' },
    { value: 'powdered milk', label: 'Powdered Milk' },
    { value: 'buttermilk', label: 'Buttermilk' },
    { value: 'whipped cream', label: 'Whipped Cream' },
    { value: 'clotted cream', label: 'Clotted Cream' },
    { value: 'mascarpone', label: 'Mascarpone' },
    { value: 'ricotta', label: 'Ricotta' },
    { value: 'creme fraiche', label: 'Creme Fraiche' },
    { value: 'yogurt drink', label: 'Yogurt Drink' },
    { value: 'smoothie', label: 'Smoothie' },
    { value: 'milkshake', label: 'Milkshake' },
    { value: 'bubble tea', label: 'Bubble Tea' },
    { value: 'iced tea', label: 'Iced Tea' },
    { value: 'hot tea', label: 'Hot Tea' },
    { value: 'green tea', label: 'Green Tea'}
]
  
  
  export default options;
  